/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gympal.view;

import gympal.controller.SocioController;
import gympal.dto.RutinaDTO;
import gympal.models.Entrenamiento;
import gympal.models.Socio;

import java.awt.event.ActionEvent;
import java.util.List;

/**
 *
 * @author Rulaai
 */
public class vistaRutina extends javax.swing.JFrame {
    SocioController controller = SocioController.getInstance();

    /**
     * Creates new form vistaRutina
     */
    public vistaRutina(RutinaDTO dto,String usuario) {
        initComponents(dto,usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(RutinaDTO dto,String usuario) {
        Socio socio = controller.obtenerSocioPorUsuario(usuario);
        List<Entrenamiento> entrenamientos= socio.getRutina().getEntrenamientos();

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comenzar = new javax.swing.JButton();
        comenzar1 = new javax.swing.JButton();
        comenzar2 = new javax.swing.JButton();
        comenzar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SEMANA 2");

        jLabel2.setText("SEMANA 1");

        jLabel3.setText("SEMANA 3");

        jLabel4.setText("SEMANA 4");

        comenzar.setText("COMENZAR");
        comenzar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                dispose();
                new vistaEntrenamiento(dto,usuario).setVisible(true);
                entrenamientos.getFirst().comenzarEntrenamiento();
            }
        });

        comenzar1.setText("COMENZAR");
        comenzar1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();

                new vistaEntrenamiento(dto,usuario).setVisible(true);
                entrenamientos.get(1).comenzarEntrenamiento();

            }
        });

        comenzar2.setText("COMENZAR");
        comenzar2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();

                new vistaEntrenamiento(dto,usuario).setVisible(true);
                entrenamientos.get(2).comenzarEntrenamiento();

            }
        });

        comenzar3.setText("COMENZAR");
        comenzar3.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();

                new vistaEntrenamiento(dto,usuario).setVisible(true);
                entrenamientos.get(3).comenzarEntrenamiento();

            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(comenzar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                        .addComponent(comenzar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comenzar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comenzar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(comenzar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(comenzar1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(comenzar2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(comenzar3))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify
    private javax.swing.JButton comenzar;
    private javax.swing.JButton comenzar1;
    private javax.swing.JButton comenzar2;
    private javax.swing.JButton comenzar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration
}
