/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gympal.view;

import gympal.controller.SocioController;
import gympal.dto.EjercicioDTO;
import gympal.dto.EntrenamientoDTO;
import gympal.dto.RutinaDTO;
import gympal.dto.SocioDTO;
import gympal.models.Ejercicio;
import gympal.models.Entrenamiento;

import java.util.List;

/**
 *
 * @author Rulaai
 */
public class vistaEntrenamiento extends javax.swing.JFrame {
    SocioController controller = SocioController.getInstance();


    /**
     * Creates new form Semana1
     */
    public vistaEntrenamiento(RutinaDTO dto,String usuario) {
        initComponents(dto,usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents(RutinaDTO dto,String usuario) {

        List<Entrenamiento> entrenamientos = dto.getEntrenamientos();
        List<Ejercicio> ejercicios= entrenamientos.getFirst().getEjercicios();



        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        series = new javax.swing.JTextField();
        repeticiones = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        grupoMuscular = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        nombre1 = new javax.swing.JTextField();
        series1 = new javax.swing.JTextField();
        repeticiones1 = new javax.swing.JTextField();
        peso1 = new javax.swing.JTextField();
        grupoMuscular1 = new javax.swing.JTextField();
        nombre2 = new javax.swing.JTextField();
        series2 = new javax.swing.JTextField();
        repeticiones2 = new javax.swing.JTextField();
        peso2 = new javax.swing.JTextField();
        grupoMuscular2 = new javax.swing.JTextField();
        nombre3 = new javax.swing.JTextField();
        series3 = new javax.swing.JTextField();
        repeticiones3 = new javax.swing.JTextField();
        peso3 = new javax.swing.JTextField();
        grupoMuscular3 = new javax.swing.JTextField();
        progresoEj1 = new javax.swing.JButton();
        progresoEj2 = new javax.swing.JButton();
        ProgresoEj4 = new javax.swing.JButton();
        progresoEj3 = new javax.swing.JButton();
        finalizarEntrenamiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NOMBRE");

        jLabel2.setText("REPETICIONES");

        jLabel3.setText("GRUPO MUSCULAR");

        jLabel4.setText("SERIES");

        jLabel5.setText("PESO");

        jLabel6.setText("NOMBRE");

        jLabel7.setText("REPETICIONES");

        jLabel8.setText("GRUPO MUSCULAR");

        jLabel9.setText("SERIES");

        jLabel10.setText("PESO");

        jLabel11.setText("NOMBRE");

        jLabel12.setText("REPETICIONES");

        jLabel13.setText("GRUPO MUSCULAR");

        jLabel14.setText("SERIES");

        jLabel15.setText("PESO");

        jLabel16.setText("NOMBRE");

        jLabel17.setText("REPETICIONES");

        jLabel18.setText("GRUPO MUSCULAR");

        jLabel19.setText("SERIES");

        jLabel20.setText("PESO");

        EjercicioDTO ej1 = ejercicios.getFirst().toDTO();
        EjercicioDTO ej2 = ejercicios.get(1).toDTO();
        EjercicioDTO ej3 = ejercicios.get(2).toDTO();
        EjercicioDTO ej4 = ejercicios.get(3).toDTO();

        series.setText(ej1.getSeries());

        repeticiones.setText(ej1.getRepeticiones());

        peso.setText(ej1.getPesoAsignado());

        grupoMuscular.setEditable(false);
        grupoMuscular.setText(ej1.getGrupoMuscular().toString());

        nombre.setText(ej1.getNombre());

        nombre1.setText(ej2.getNombre());

        series1.setText(ej2.getSeries());

        repeticiones1.setText(ej2.getRepeticiones());

        peso1.setText(ej2.getPesoAsignado());

        grupoMuscular1.setEditable(false);
        grupoMuscular1.setText(ej2.getGrupoMuscular().toString());

        nombre2.setText(ej3.getNombre());

        series2.setText(ej3.getSeries());

        repeticiones2.setText(ej3.getRepeticiones());

        peso2.setText(ej3.getPesoAsignado());

        grupoMuscular2.setEditable(false);
        grupoMuscular2.setText(ej3.getGrupoMuscular().toString());

        nombre3.setText(ej4.getNombre());

        series3.setText(ej4.getSeries());

        repeticiones3.setText(ej4.getRepeticiones());

        peso3.setText(ej4.getPesoAsignado());

        grupoMuscular3.setEditable(false);
        grupoMuscular3.setText(ej4.getGrupoMuscular().toString());

        progresoEj1.setText("REGISTRAR PROGRESO");
        progresoEj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicios.getFirst().registrarProgreso(Integer.parseInt(series.getText()),Integer.parseInt(repeticiones.getText()) ,Double.parseDouble(peso.getText()));
                System.out.println("Progreso Registrado con exito");
                progresoEj1ActionPerformed(evt);
            }
        });

        progresoEj2.setText("REGISTRAR PROGRESO");
        progresoEj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicios.get(1).registrarProgreso(Integer.parseInt(series1.getText()),Integer.parseInt(repeticiones1.getText()) ,Double.parseDouble(peso1.getText()));
                System.out.println("Progreso Registrado con exito");
                progresoEj2ActionPerformed(evt);
            }
        });

        ProgresoEj4.setText("REGISTRAR PROGRESO");
        ProgresoEj4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicios.get(3).registrarProgreso(Integer.parseInt(series3.getText()),Integer.parseInt(repeticiones3.getText()) ,Double.parseDouble(peso3.getText()));
                System.out.println("Progreso Registrado con exito");
                ProgresoEj4ActionPerformed(evt);
            }
        });

        progresoEj3.setText("REGISTRAR PROGRESO");
        progresoEj3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejercicios.get(2).registrarProgreso(Integer.parseInt(series2.getText()),Integer.parseInt(repeticiones2.getText()) ,Double.parseDouble(peso2.getText()));
                System.out.println("Progreso Registrado con exito");
                progresoEj3ActionPerformed(evt);
            }
        });

        finalizarEntrenamiento.setText("FINALIZAR ENTRENAMIENTO");
        finalizarEntrenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SocioDTO socioDto= controller.obtenerSocioPorUsuario(usuario).toDTO();
                dispose();
                new vistaUsuario(socioDto).setVisible(true);
                finalizarEntrenamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(8, 8, 8)
                                                                        .addComponent(jLabel6))
                                                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addGap(7, 7, 7)
                                                                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(8, 8, 8)
                                                                        .addComponent(jLabel1)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel16)
                                                                        .addComponent(nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(36, 36, 36)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(2, 2, 2)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel9)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel7)
                                                                                .addGap(27, 27, 27)
                                                                                .addComponent(jLabel10)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel8))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel14)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel12)
                                                                                .addGap(27, 27, 27)
                                                                                .addComponent(jLabel15)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel13))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel19)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel17)
                                                                .addGap(27, 27, 27)
                                                                .addComponent(jLabel20)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel18))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(2, 2, 2)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel4)
                                                                                        .addComponent(series, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(repeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel5)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel3))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(grupoMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(12, 12, 12))))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(1, 1, 1)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(series1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(repeticiones1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(peso1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(grupoMuscular1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(series2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(repeticiones2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(peso2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(grupoMuscular2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(1, 1, 1)
                                                                                .addComponent(series3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(repeticiones3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(peso3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(grupoMuscular3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(23, 23, 23)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(progresoEj1)
                                                                        .addComponent(progresoEj2)
                                                                        .addComponent(ProgresoEj4)
                                                                        .addComponent(progresoEj3)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(244, 244, 244)
                                                .addComponent(finalizarEntrenamiento)))
                                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel1))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(series, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(repeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(grupoMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(progresoEj1))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(series1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(repeticiones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(peso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(grupoMuscular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(progresoEj2))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(series2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(repeticiones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(peso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(grupoMuscular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(progresoEj3))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(series3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(repeticiones3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(peso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(grupoMuscular3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ProgresoEj4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(finalizarEntrenamiento)
                                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>

    private void progresoEj1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void progresoEj2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ProgresoEj4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void progresoEj3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void finalizarEntrenamientoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify
    private javax.swing.JButton ProgresoEj4;
    private javax.swing.JButton finalizarEntrenamiento;
    private javax.swing.JTextField grupoMuscular;
    private javax.swing.JTextField grupoMuscular1;
    private javax.swing.JTextField grupoMuscular2;
    private javax.swing.JTextField grupoMuscular3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    private javax.swing.JTextField nombre3;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField peso1;
    private javax.swing.JTextField peso2;
    private javax.swing.JTextField peso3;
    private javax.swing.JButton progresoEj1;
    private javax.swing.JButton progresoEj2;
    private javax.swing.JButton progresoEj3;
    private javax.swing.JTextField repeticiones;
    private javax.swing.JTextField repeticiones1;
    private javax.swing.JTextField repeticiones2;
    private javax.swing.JTextField repeticiones3;
    private javax.swing.JTextField series;
    private javax.swing.JTextField series1;
    private javax.swing.JTextField series2;
    private javax.swing.JTextField series3;
    // End of variables declaration
}
